# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20170315_0201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='ingredient',
            field=models.ManyToManyField(to='menu.Ingredient'),
        ),
    ]
